// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// PLACEHOLDER VALUES — replace this whole file by running:
///   flutterfire configure
/// once you have a real Firebase project set up.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk31cWFwZwQOX42PC_eamavnIaeZssE0A',
    appId: '1:147982704006:android:a4c804a0752c3c72a12007',
    messagingSenderId: '147982704006',
    projectId: 'lm-plus-locator',
    storageBucket: 'lm-plus-locator.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7vfd67N-XZnuJFUKqbiAosV50swMPzCM',
    appId: '1:147982704006:ios:52b032cdabbc0804a12007',
    messagingSenderId: '147982704006',
    projectId: 'lm-plus-locator',
    storageBucket: 'lm-plus-locator.firebasestorage.app',
    iosBundleId: 'me.symon.lmplusLocator',
  );
}
